data_pipeline/dags/banner_data_dag.py, data_pipeline/dags/scripts/fetch_banner_data.py
- using base url from airflow variables
- corrected passing of inputs between the dags
=> Banner api

data_pipeline/dags/scripts/fetch_banner_data.py
=> Updated term to spring

data_pipeline/dags/scripts/fetch_banner_data.py
=> changed post request

data_pipeline/dags/banner_data_dag.py, data_pipeline/dags/scripts/extract_data.py, data_pipeline/dags/scripts/fetch_banner_data.py
- fixed csv issues
- increased course limit to 1100
=> fixed csv issues

data_pipeline/dags/scripts/fetch_banner_data.py
=> pushing to trigger action

data_pipeline/dags/scripts/data_utils.py, data_pipeline/dags/scripts/fetch_banner_data.py
- some more logging
- comments
- Skipping courses that have no faculty name available
=> Code cleanup and refactoring

data_pipeline/dags/scripts/extract_trace_data.py, data_pipeline/dags/scripts/fetch_banner_data.py
- term description
- lecture days
- lecture start and end time
=> Changes to banner data fields

data_pipeline/dags/banner_data_dag.py, data_pipeline/dags/main.py, data_pipeline/dags/scripts/fetch_banner_data.py, data_pipeline/tests/test_extract_data.py, data_pipeline/tests/test_fetch_banner_data.py
- file name
- import errors
- csv columns
=> Fixed errors:

data_pipeline/dags/scripts/fetch_banner_data.py
=> testing csv errors

data_pipeline/dags/scripts/fetch_banner_data.py
- removed check for faculty name, 
- no names available currently max limit per request is 500, need to handle multiple requests later
=> Fixed banner issues:

.github/workflows/python-tests.yaml, data_pipeline/dags/scripts/fetch_banner_data.py, data_pipeline/tests/test_extract_data.py, data_pipeline/tests/test_fetch_banner_data.py
Fixed test cases after change in code
=> Fixed test cases

data_pipeline/dags/scripts/fetch_banner_data.py
- import format not working in the dag, but this won't work in the test
=> reverted import

data_pipeline/dags/banner_data_dag.py, data_pipeline/dags/scripts/fetch_banner_data.py
- fetching faculty name
- meeting info
- added new node in the dag
=> Added new banner api

data_pipeline/dags/banner_data_dag.py, data_pipeline/dags/scripts/fetch_banner_data.py
- added new banner api for fetching prereqs
- added new column to csv
=> Added course prerequisites

data_pipeline/dags/scripts/fetch_banner_data.py
=> Corrected csv dump for prereq

data_pipeline/dags/banner_data_dag.py, data_pipeline/dags/scripts/opt_fetch_banner_data.py
- testing banner dag with optimized code.
- testing only csv for now
=> Optimize banner dag

data_pipeline/dags/banner_data_dag.py, data_pipeline/dags/scripts/opt_fetch_banner_data.py
- Parallelized the api calls using thread pool executor and tested the output
- added the gcs to bq node back to the dag
=> Final changes for optimized DAG

data_pipeline/dags/banner_data_dag.py, data_pipeline/dags/main.py, data_pipeline/dags/train_data_dag.py
- added email triggers for all 3 dags
- configured email params in gcp
=> Email triggers

data_pipeline/dags/scripts/fetch_banner_data.py, data_pipeline/dags/scripts/opt_fetch_banner_data.py
- skipping courses with no faculty name
- added more logging for debuggin
=> Logs and alerts

data_pipeline/dags/scripts/fetch_banner_data.py, data_pipeline/dags/scripts/opt_fetch_banner_data.py
- converted course list output to json
- added more error handling
=> added more logging and data handling

data_pipeline/dags/banner_data_dag.py, data_pipeline/dags/scripts/fetch_banner_data.py
- removing courses without faculty info
=> added task:

data_pipeline/dags/scripts/fetch_banner_data.py, data_pipeline/dags/scripts/opt_fetch_banner_data.py
- changed course list to pandas dataframe
- passing data using xcom pull
=> Changed datatype of course list to pd dataframe

data_pipeline/dags/scripts/fetch_banner_data.py
Corrected formatting of dataframe
=> Changed df formatting

data_pipeline/dags/scripts/banner/fetch_banner_data.py, data_pipeline/dags/scripts/data/data_anomalies.py, data_pipeline/dags/scripts/data/data_utils.py, data_pipeline/dags/scripts/email_triggers.py
- email trigger for missing faculty
- refactored helper methods to data utils
=> Refactored and added trigger:

.github/workflows/trigger-banner-dag.yaml, data_pipeline/dags/scripts/banner/fetch_banner_data.py
=> Banner dag action

.github/workflows/trigger-banner-dag.yaml, model_training/dags/model_scripts/prompts.py, model_training/dags/train_model_trigger_tag.py
=> Bias check

README.md, model_training/dags/train_eval_model_trigger_dag.py
- Added email triggers
- updated readme
=> Model pipeline

model_deployment/app/constants/bq_queries.py, model_deployment/app/constants/requests.py, model_deployment/app/routers/llm_router.py, model_deployment/app/services/llm_service.py, model_deployment/app/utils/bq_utils.py
- changes for saving session 
- fetching cached context based on session
=> Maintaining session for chatbot

backend/app/constants/bq_queries.py, backend/app/constants/prompts.py, backend/app/constants/requests.py, backend/app/main.py, backend/app/routers/feedback.py, backend/app/routers/llm_router.py, backend/app/services/feedback_service.py, backend/app/services/llm_service.py, backend/app/utils/bq_utils.py
- Added endpoint for user feedback
- added a prompt along with the query and context for the llm for better responses, still needs to be worked on
- generating a unique query_id for each query, and sending it in the response so that it can be used in the frontend when sending the feedback for that particular query.
=> User feedback
